name: Go

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: can
     
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Build web api
      run: |
        echo "HI ${NAME}"
    
    
    - name: Build
      run:  GOOS=linux GOARCH=amd64 go build -o lol hello/hello.go
      
    - name: Run latest-tag
      uses: EndBug/latest-tag@latest
      with:
        description: Description for the tag
      
    - name: upload another lib  
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "lol"
        overwrite: true
        draft: false

       

