name: Go

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Build
      run:  go build -o lol hello/hello.go

      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binary
        path: ${{github.workspace}}/lol
        
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          
    - name: Upload release binary
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path:  ${{github.workspace}}/lol
        asset_name: lol
        asset_content_type: application/octet-stream
    
